# Generated by Django 5.2.dev20240724125510 on 2024-07-24 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen"),
                            ("common_area", "Common Area"),
                            ("it_room", "IT Room"),
                            ("webinar_room", "Webinar Room"),
                            ("work_room", "Work Room"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("capacity", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("name", "number")},
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.room"
                    ),
                ),
            ],
        ),
    ]
